# Generated by Django 5.1.4 on 2025-01-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('finance', 'Finance'), ('sports', 'Sports'), ('technology', 'Technology'), ('health', 'Health'), ('entertainment', 'Entertainment')], max_length=50),
        ),
    ]
